# This script tests the functionality of the odds scraping

Simply run the code below and check the outputs against the linked websites

In [1]:
import requests
# from bs4 import BeautifulSoup
# import pandas as pd
# import numpy as np
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.firefox.service import Service
import urllib.parse

In [2]:
# Change to the correct working directory then load the global
%cd ..

E:\Repos\mma_model

In [3]:
exec(open("./global.py").read())

fighter_list = ["Fernando Gonzalez Trevino", "Jose Aldo"]

In [4]:
# Run the single function
scrape_fighter_odds(fighter_list[0])

Found string: Fernando Gonzalez Trevino, Link: https://www.bestfightodds.com/fighters/Fernando-Gonzalez-Trevino-9628

,open_odds,closing_odds_low,closing_odds_high,event,date,fighter,opponent
0,-170,-175,-167,Combate 49: San Antonio,2019-11-08,Fernando Gonzalez Trevino,Cesar Arzamendia
1,-150,-160,-155,Combate 47: Monterrey,2019-10-18,Fernando Gonzalez Trevino,Alvaro Herrera

Check this output against the link above.

In [9]:
# Run the parallel scrape
## AB: THIS ISN'T WORKING. NOT SURE WHY.

parallel_scrape_odds(fighter_list, num_threads=3, firefox_location=config["firefox_location"], gecko_driver=config["gecko_driver_location"])

Found string: Conor McGregor, Link: https://www.bestfightodds.com/fighters/Conor-McGregor-3147
Found string: Jose Aldo, Link: https://www.bestfightodds.com/fighters/Jose-Aldo-659

,open_odds,closing_odds_low,closing_odds_high,event,date,fighter,opponent
0,-150,-150,-150,Future Events,NaT,Conor McGregor,Mike Perry
1,-300,-280,-255,Future Events,NaT,Conor McGregor,Tony Ferguson
2,-120,+100,+100,UFC,2024-06-29,Conor McGregor,Michael Chandler
3,+110,-130,-115,UFC,2023-12-31,Conor McGregor,Michael Chandler
4,-450,-450,-450,UFC,2023-07-30,Conor McGregor,Ronda Rousey
5,-140,+100,+115,UFC 264: Poirier vs. McGregor 3,2021-07-10,Conor McGregor,Dustin Poirier
6,-175,-333,-290,UFC 257: Poirier vs. McGregor 2,2021-01-23,Conor McGregor,Dustin Poirier
7,+175,+162,+169,UFC 229: Nurmagomedov vs. McGregor,2018-10-06,Conor McGregor,Khabib Nurmagomedov
8,-280,-475,-425,UFC 196: McGregor vs. Diaz,2016-03-05,Conor McGregor,Nate Diaz
9,-180,-108,-105,UFC 194: Aldo vs. McGregor,2015-12-12,Conor McGregor,Jose Aldo
10,+100,-190,-175,UFC 189: Mendes vs. McGregor,2015-07-11,Conor McGregor,Chad Mendes
11,-600,-1000,-975,UFC Fight Night 59: McGregor vs. Siver,2015-01-18,Conor McGregor,Dennis Siver
12,-170,-260,-255,UFC 178: Johnson vs. Cariaso,2014-09-27,Conor McGregor,Dustin Poirier
13,-385,-690,-600,UFC Fight Night 46: McGregor vs. Brandao,2014-07-19,Conor McGregor,Diego Brandao
14,-165,-333,-290,UFC 246: McGregor vs. Cowboy,2020-01-18,Conor McGregor,Donald Cerrone
15,-145,-161,-160,UFC 205: Alvarez vs. McGregor,2016-11-12,Conor McGregor,Eddie Alvarez
16,-130,-142,-135,UFC 202: Diaz vs. McGregor 2,2016-08-20,Conor McGregor,Nate Diaz
17,-190,-290,-245,UFC Fight Night 26: Shogun vs. Sonnen,2013-08-17,Conor McGregor,Max Holloway
18,-170,-160,-150,UFC on Fuel TV 9: Mousasi vs. Latifi,2013-04-06,Conor McGregor,Marcus Brimage
19,-180,-140,-140,Cage Warriors 51,2012-12-31,Conor McGregor,Ivan Buchinger
20,-290,-245,-245,Cage Warriors 47,2012-06-02,Conor McGregor,Dave Hill
21,-205,-205,-205,Cage Warriors 45: Lloret vs. Brents,2012-02-18,Conor McGregor,Steve Okeeffe
0,+130,+130,+138,UFC 307,2024-10-05,Jose Aldo,Mario Bautista
1,-107,+120,+150,UFC,2024-05-05,Jose Aldo,Jonathan Martinez
2,-2000,-2100,-2100,Shooto Brazil Boxing,2023-02-10,Jose Aldo,Alberto Zambrano
3,-170,+100,+145,UFC 278: Usman vs. Edwards 2,2022-08-20,Jose Aldo,Merab Dvalishvili
4,-105,+105,+125,UFC Fight Night: Font vs. Aldo,2021-12-04,Jose Aldo,Rob Font
5,-138,-125,-102,UFC 265: Lewis vs. Gane,2021-08-07,Jose Aldo,Pedro Munhoz
6,-125,-161,-137,UFC Fight Night 183: Thompson vs. Neal,2020-12-19,Jose Aldo,Marlon Vera
7,+205,+200,+230,UFC 251: Usman vs. Masvidal,2020-07-11,Jose Aldo,Petr Yan
8,-185,-152,-145,UFC 237: Namajunas vs. Andrade,2019-05-11,Jose Aldo,Alex Volkanovski
9,-120,-110,+100,UFC on ESPN+ 2: Assuncao vs. Moraes 2,2019-02-02,Jose Aldo,Renato Moicano
10,-135,-103,+100,UFC on FOX 30: Alvarez vs. Poirier 2,2018-07-28,Jose Aldo,Jeremy Stephens
11,+190,+220,+225,UFC 218: Holloway vs. Aldo 2,2017-12-02,Jose Aldo,Max Holloway
12,-130,-151,-145,UFC 212: Aldo vs. Holloway,2017-06-03,Jose Aldo,Max Holloway
13,-130,+113,+120,UFC 200: Tate vs. Nunes,2016-07-09,Jose Aldo,Frankie Edgar
14,+150,-115,-112,UFC 194: Aldo vs. McGregor,2015-12-12,Jose Aldo,Conor McGregor
15,-190,-220,-200,UFC 179: Aldo vs. Mendes II,2014-10-25,Jose Aldo,Chad Mendes
16,-600,-800,-750,UFC 169: Barao vs. Faber,2014-02-01,Jose Aldo,Ricardo Lamas
17,+135,+142,+150,UFC 245: Usman vs. Covington,2019-12-14,Jose Aldo,Marlon Moraes
18,-505,-900,-875,UFC 163: Aldo vs. Jung,2013-08-03,Jose Aldo,Chan Sung Jung
19,-195,-185,-175,UFC 156: Aldo vs. Edgar,2013-02-02,Jose Aldo,Frankie Edgar
20,-320,-230,-230,UFC 142: Aldo vs. Mendes,2012-01-14,Jose Aldo,Chad Mendes
21,-250,-355,-355,UFC 136: Edgar vs. Maynard 3,2011-10-08,Jose Aldo,Kenny Florian
22,-450,-500,-500,UFC 129: St-Pierre vs. Shields,2011-04-30,Jose Aldo,Mark Hominick
23,-420,-560,-560,WEC 51: Aldo vs. Gamburyan,2010-09-30,Jose Aldo,Manny Gamburyan
24,-350,-315,-315,WEC 48: Aldo vs. Faber,2010-04-24,Jose Aldo,Urijah Faber
25,+105,+110,+110,WEC 44: Brown vs Aldo,2009-11-18,Jose Aldo,Mike Brown
26,-385,-360,-360,WEC 41: Brown vs Faber 2,2009-06-07,Jose Aldo,Cub Swanson
27,-1175,-1000,-1000,WEC 39: Brown vs Garcia,2009-03-01,Jose Aldo,Chris Mickle
28,-900,-900,-900,WEC 38: Varner vs Cerrone,2009-01-25,Jose Aldo,Rolando Perez
29,-435,-485,-485,WEC 36: Faber vs Brown,2008-11-05,Jose Aldo,Jonathan Brookins
30,+168,+215,+215,WEC 34: Faber vs Pulver,2008-06-01,Jose Aldo,Alexandre Nogueira

Check this against the odds webpages
https://www.bestfightodds.com/fighters/Conor-McGregor-3147
https://www.bestfightodds.com/fighters/Jose-Aldo-659